services:
  api:
    build: ./flask_app
    ports:
      - "8000:80"
    volumes:
      - ./flask_app:/api
    environment:
      FLASK_ENV: development
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - api