services:
  api:
    build: ./flask_app
    ports:
      - "8000:80"
    volumes:
      - ./flask_app:/api
    environment:
      FLASK_ENV: development
  web:
    build: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api