services:
  api:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    image: "haymarnhm/currency-exchange-api:v1.0.0"
    ports:
      - "8000:80"
    volumes:
      - ./flask_app:/api
    environment:
      FLASK_ENV: development
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: "haymarnhm/currency-exchange-web:v1.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - api