Description: >
  CurrencyExchange web-app stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub CurrencyExchange-${ID}
      GroupDescription: Allow port 22, 3030 and 9100.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3030'
          ToPort: '3030'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '9100'
          ToPort: '9100'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8000'
          ToPort: '8000'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: uswest2-project-udacity
      ImageId: ami-0ddf424f81ddb0720
      Tags:
        - Key: Name
          Value: !Sub currency-exchange-${ID}

Outputs:
  WorkflowID:
    Value: !GetAtt EC2Instance.PublicIp
    Description: PublicIP for CurrencyExchange
    Export:
      Name: !Sub currency-exchange-${ID}