version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
  python3: 
  
jobs:
  build-infrastructure:
    docker:
      - image: amazon/aws-cli
    parameters:
      cluster-role-name:
        description: |
          Name of IAM Role
        type: string
    steps:
      - checkout
      - run:
          name: Ensure VPC exist for EKS cluster
          command: |
            aws ec2 \
              --output text \
              --query 'Vpcs[*].{VpcId:VpcId,Name:Tags[?Key==`Name`].Value|[0],CidrBlock:CidrBlock}' \
              describe-vpcs
      - run:
          name: Ensure IAM Roles exist for EKS cluster
          command: |
            aws iam get-role \
              --role-name << parameters.cluster-role-name >>

  # create-cluster is done by orbs
  test-cluster:
    docker:
      - image: cimg/python:3.10.4
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
          name: Test cluster

workflows:
  deployment:
    jobs:
      - build-infrastructure:
          cluster-role-name: $IAM_ROLE_NAME
      - aws-eks/delete-cluster:
          cluster-name: demo-cluster-01
      - aws-eks/create-cluster:
          cluster-name: demo-cluster-02
      - test-cluster:
          cluster-name: demo-cluster-02
          requires:
            - aws-eks/create-cluster