# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs: 
  build-backend:
    docker:
      # Use the same Docker base as the ./flask_app/Dockerfile
      - image: python:3.7.3-stretch 
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./flask_app/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            cd ./flask_app/
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "./flask_app/requirements.txt" }}
      - run:
          name: run lint
          command: |
            cd ./flask_app/
            . venv/bin/activate
            make lint

  build-frontend:
    docker:
      # Use the same Node base as ./client/Dockerfile
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - restore_cache:
          key: frontend-build-{{ checksum "./client/package-lock.json" }}
      - run:
          name: Build front-end
          command: |
            cd ./client
            sudo npm install
            npm run build
      - save_cache:
          paths: [./frontend/node_modules]
          key: frontend-build-{{ checksum "./client/package-lock.json" }}

  test-frontend:
    docker:
      # Use the same Node base as ./client/Dockerfile
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - restore_cache:
          key: frontend-build-{{ checksum "./client/package-lock.json" }}
      - run:
          name: Test front-end
          command: |
            cd ./client
            sudo npm install
            npm run test

  eslint-frontend:
    docker:
      # Use the same Node base as ./client/Dockerfile
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - restore_cache:
          key: frontend-build-{{ checksum "./client/package-lock.json" }}
      - run:
          name: Eslint front-end
          command: |
            cd ./client
            sudo npm install
            npm run lint

workflows:
  version: 2
  default:
    jobs:
      - build-backend
      - build-frontend
      - test-frontend:
          requires:
            - build-frontend
      - eslint-frontend:
          requires:
            - build-frontend
      